### ISSUE TITLE
No need to unwrap object

### ISSUE THREAD

**Issue by john-terenzio** [CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency#1]
https://github.com/CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency/blob/f6c2ef6e1acf3515060b56208a9cf6fbad551aa6/javascript.js#L69-L74

Seems like instead of copying the keys of `data[game]` to a new object, you could probably just do this:
```js
var html = template(data[game]);
```

**Comment by john-terenzio** [comment]
Since you already have an object in the exact format you want.

**Comment by CodyvanderPoel** [comment]
I just tried that out and it works perfectly! Thanks for that!
