### ISSUE TITLE
Rental form should be styled with Bootstrap

### ISSUE THREAD

**Issue by natec425** [CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency#2]
https://github.com/CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency/blob/19faf66d2edf86148416a6178bbc702258a86ad9/index.html#L84-L106

One of the purposes of this exercise is to use Bootstrap effectively. Part of that is using Bootstrap's functionality around forms.

Bootstrap form docs: http://getbootstrap.com/docs/4.1/components/forms/

It might be best to focus on `form-group` and `form-control` first ([docs](http://getbootstrap.com/docs/4.1/components/forms/#form-controls)).

Using `help-text` well is a good next step ([docs](http://getbootstrap.com/docs/4.1/components/forms/#help-text))

Finally, I think you should look at Bootstrap's form validation helpers. Specifically, I'm linking you to the "server-side" section. You can mostly ignore that and focus on how to use the `is-valid`, `is-invalid`, `valid-feedback`, and `invalid-feedback` classes ([docs](http://getbootstrap.com/docs/4.1/components/forms/#server-side))

**Comment by CodyvanderPoel** [comment]
I didn't realize that Bootstrap covered forms as well, but now that it is implemented the mobile version's form looks so much better. Thanks for the tip!
