### ISSUE TITLE
Make sure attributes have quotes around their values

### ISSUE THREAD

**Issue by natec425** [CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency#3]
https://github.com/CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency/blob/19faf66d2edf86148416a6178bbc702258a86ad9/index.html#L65

**Comment by CodyvanderPoel** [comment]
Was this the only line you could find that on?

**Comment by natec425** [comment]
I can't remember. I would suggest double checking for yourself though.

**Comment by CodyvanderPoel** [comment]
Can do.
