### ISSUE TITLE
Use the margin shorthand property instead of multiple declarations.

### ISSUE THREAD

**Issue by natec425** [CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency#5]
https://github.com/CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency/blob/19faf66d2edf86148416a6178bbc702258a86ad9/style.css#L3-L5

https://github.com/CodyvanderPoel/Cody-van-der-Poel--Web-Rental-Agency/blob/19faf66d2edf86148416a6178bbc702258a86ad9/style.css#L19-L22

Here is the MDN docs for [margin](https://developer.mozilla.org/en-US/docs/Web/CSS/margin#Syntax)

**Comment by CodyvanderPoel** [comment]
This is okay right?
`margin: 4.5rem;
    margin-top:0rem;`

**Comment by natec425** [comment]
I would do `margin: 0 4.5rem 4.5rem 4.5rem;`
